server:
  port: 8001


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10KB

storage:
  upload-dir: D:/upload/